spring:
  cloud:
    config:
      auto-refresh: true
      refresh-interval: 30
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}